Added Footer folder/to main.jsx
shaaronl/jukeboxd pull request #41
Opened 2024-05-20 20:09 UTC by BraedenAlonge

2024-05-20 20:11 UTC, BraedenAlonge commented
Footer not showing up.

2024-05-21 01:19 UTC, shaaronl requested changes

2024-05-21 01:19 UTC, shaaronl commented on packages/react-frontend/src/App.jsx
hmm i think the reason why it's nw showing up is because it's put inside of app.jsx...i think you have to put it inside of the root.jsx folder inside of the folder routes

2024-05-21 01:19 UTC, shaaronl commented on packages/react-frontend/src/main.jsx
this looks good!

2024-05-21 01:19 UTC, shaaronl commented on packages/react-frontend/src/routes/Footer/Styles/Footer.jsx
is this just equivalent to a css file?

2024-05-22 02:33 UTC, saravoong commented on packages/react-frontend/src/routes/Footer/Styles/Footer.jsx
Not sure about this, if it's supposed to be a CSS file, should probably convert to one because majority of our styling are in css files.

2024-05-22 02:33 UTC, saravoong commented on packages/react-frontend/src/routes/Footer/index.jsx
what do the children do?

2024-05-23 05:39 UTC, closed without merging